### PR TITLE
Explicitly ignore routing errors by using the MustRoute function

### PR DESCRIPTION
**Pull request by asif-ir**
Just to calm IDEs down.

### CODE REVIEW

**Comment by danielpoe** [comment]
Which IDE are you using.
Goland does not complain and we use this syntax in many places.

Maybe there is a configuration option in the IDE?

**Comment by asif-ir** [comment]
I use Goland too. This is not a biggie but definitely annoying.

image

Notice the difference between the 2 ways above.

**Comment by danielpoe** [comment]
Hmm not for me. Also golint does not complain.
Would be good to know the Goland config or extension that complains about this

**Comment by carstendietrich** [comment]
@asif-ir thanks for the contribution, you're right it would be better to explicitly ignore those errors. We introduced a `MustRoute` function for that use case in v3.2.0 and forgot to update this example.

https://github.com/i-love-flamingo/flamingo/blob/6601f552b0776ca14a057ed367ac37b21359d6f3/framework/web/registry.go#L178

Do you want to update your PR (updating flamingo to 3.2.0 and using MustRoute)?

**Comment by asif-ir** [comment]
Looks good now.

**Comment by carstendietrich** [comment]
> Looks good now.

Cool, could you please update the Readme.md as well? Should be then ready for merge 👍

**Comment by asif-ir** [comment]
Thank you @danielpoe :)

**Pull request merged**
